name: Bug report
description: Report a reproducible bug
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the problem clearly.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps, commands, and inputs.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Provide versions and OS details.
      placeholder: |
        browser-use:
        node:
        pnpm:
        os:
    validations:
      required: true
