/**
 * Optimized Chrome arguments for browser automation
 */

/**
 * Chrome debug port - use non-default to avoid conflicts
 */
export const CHROME_DEBUG_PORT = 9242;

/**
 * Chrome features to disable for better automation compatibility
 * Based on Playwright defaults and browser-use optimizations
 */
export const CHROME_DISABLED_COMPONENTS = [
  // Playwright defaults
  'AcceptCHFrame',
  'AutoExpandDetailsElement',
  'AvoidUnnecessaryBeforeUnloadCheckSync',
  'CertificateTransparencyComponentUpdater',
  'DestroyProfileOnBrowserClose',
  'DialMediaRouteProvider',
  'ExtensionManifestV2Disabled',
  'GlobalMediaControls',
  'HttpsUpgrades',
  'ImprovedCookieControls',
  'LazyFrameLoading',
  'LensOverlay',
  'MediaRouter',
  'PaintHolding',
  'ThirdPartyStoragePartitioning',
  'Translate',

  // Additional optimizations for automation
  'AutomationControlled',
  'BackForwardCache',
  'OptimizationHints',
  'ProcessPerSiteUpToMainFrameThreshold',
  'InterestFeedContentSuggestions',
  'CalculateNativeWinOcclusion',
  'HeavyAdPrivacyMitigations',
  'PrivacySandboxSettings4',
  'AutofillServerCommunication',
  'CrashReporting',
  'OverscrollHistoryNavigation',
  'InfiniteSessionRestore',
  'ExtensionDisableUnsupportedDeveloper',
];

/**
 * Headless mode arguments
 */
export const CHROME_HEADLESS_ARGS = ['--headless=new'];

/**
 * Docker-specific arguments for better compatibility
 */
export const CHROME_DOCKER_ARGS = [
  '--no-sandbox',
  '--disable-gpu-sandbox',
  '--disable-setuid-sandbox',
  '--disable-dev-shm-usage',
  '--no-xshm',
  '--no-zygote',
  '--disable-site-isolation-trials',
];

/**
 * Security-disabled arguments for testing environments
 */
export const CHROME_DISABLE_SECURITY_ARGS = [
  '--disable-site-isolation-trials',
  '--disable-web-security',
  '--disable-features=IsolateOrigins,site-per-process',
  '--allow-running-insecure-content',
  '--ignore-certificate-errors',
  '--ignore-ssl-errors',
  '--ignore-certificate-errors-spki-list',
];

/**
 * Deterministic rendering arguments for consistent screenshots
 */
export const CHROME_DETERMINISTIC_RENDERING_ARGS = [
  '--deterministic-mode',
  '--js-flags=--random-seed=1157259159',
  '--force-device-scale-factor=2',
  '--enable-webgl',
  '--font-render-hinting=none',
  '--force-color-profile=srgb',
];

/**
 * Core optimized Chrome arguments for automation
 * These are carefully selected for reliable browser automation
 */
export const CHROME_OPTIMIZED_ARGS = [
  // Network and background processing
  '--disable-field-trial-config',
  '--disable-background-networking',
  '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-back-forward-cache',

  // Security and safety (for automation)
  '--disable-breakpad',
  '--disable-client-side-phishing-detection',
  '--disable-component-extensions-with-background-pages',
  '--disable-component-update',
  '--no-default-browser-check',
  '--disable-dev-shm-usage',

  // Performance and stability
  '--disable-hang-monitor',
  '--disable-ipc-flooding-protection', // Critical: allows rapid CDP calls
  '--disable-popup-blocking',
  '--disable-prompt-on-repost',
  '--disable-renderer-backgrounding',
  '--metrics-recording-only',
  '--no-first-run',
  '--password-store=basic',
  '--use-mock-keychain',
  '--no-service-autorun',
  '--export-tagged-pdf',
  '--disable-search-engine-choice-screen',
  '--unsafely-disable-devtools-self-xss-warnings',

  // Automation optimization
  '--enable-features=NetworkService,NetworkServiceInProcess',
  '--enable-network-information-downlink-max',
  '--test-type=gpu',
  '--disable-sync',
  '--allow-legacy-extension-manifests',
  '--allow-pre-commit-input',
  '--disable-blink-features=AutomationControlled', // Hide automation detection
  '--install-autogenerated-theme=0,0,0',
  '--log-level=2',
  '--disable-focus-on-load',
  '--disable-window-activation',
  '--generate-pdf-document-outline',
  '--no-pings',
  '--ash-no-nudges',
  '--disable-infobars',
  '--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT"',
  '--hide-crash-restore-bubble',
  '--suppress-message-center-popups',
  '--disable-domain-reliability',
  '--disable-datasaver-prompt',
  '--disable-speech-synthesis-api',
  '--disable-speech-api',
  '--disable-print-preview',
  '--safebrowsing-disable-auto-update',
  '--disable-external-intent-requests',
  '--disable-desktop-notifications',
  '--noerrdialogs',
  '--silent-debugger-extension-api',
  '--disable-extensions-http-throttling',
  '--extensions-on-chrome-urls',
  '--disable-default-apps',
  `--disable-features=${CHROME_DISABLED_COMPONENTS.join(',')}`,
];

/**
 * Stealth mode arguments to avoid detection
 */
export const CHROME_STEALTH_ARGS = [
  '--disable-blink-features=AutomationControlled',
  '--exclude-switches=enable-automation',
  '--disable-web-security',
  '--disable-infobars',
  '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
];

/**
 * Extension-related arguments
 */
export const CHROME_EXTENSION_ARGS = [
  '--enable-extensions',
  '--disable-extensions-file-access-check',
  '--disable-extensions-http-throttling',
  '--enable-extension-activity-logging',
];

/**
 * Playwright default Chromium arguments to ignore/disable
 * remove easily detectable automation flags
 * and allow extensions, scrollbars, etc.
 */
export const PLAYWRIGHT_IGNORED_DEFAULT_ARGS: string[] = [
  '--enable-automation',
  '--disable-extensions',
  '--hide-scrollbars',
  '--disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DeferRendererTasksAfterInput,DestroyProfileOnBrowserClose,DialMediaRouteProvider,ExtensionManifestV2Disabled,GlobalMediaControls,HttpsUpgrades,ImprovedCookieControls,LazyFrameLoading,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate',
];
